jobs:
  include:
  - stage: deploy-native-mac
    os: osx
    language: java
    osx_image: xcode11
    before_install:
    - curl -sL https://get.sdkman.io | bash
    - echo sdkman_auto_answer=true > $HOME/.sdkman/etc/config
    - source "$HOME/.sdkman/bin/sdkman-init.sh"
    install:
    - sdk install java $(sdk list java | grep -o "8\.[0-9\.]*hs-adpt" | head -1)
    script:
    - "./gradlew clean"
    - travis_wait 40 ./gradlew --stacktrace native-cli:distro
    deploy:
    - provider: script
      skip_cleanup: true
      script: "./gradlew native-cli:uploadDistro"
      on:
        branch: master
  - stage: deploy-native-linux
    os: linux
    language: java
    jdk: openjdk8
    script:
    - travis_wait 40 ./gradlew --stacktrace native-cli:distro
    deploy:
    - provider: script
      skip_cleanup: true
      script: "./gradlew native-cli:uploadDistro"
      on:
        branch: master
notifications:
  slack:
    rooms:
      secure: DECkszcV0kRxQS8jwQaUl3sotWsPsKuvlvo5b+Boch8HVIGnVIin8ka909HEZdMkSZ7MHKyMHPOV70MTZwlRZuvnocHscQDFJHifU5HHG2CatU2n670uJ4UpWlPpPMobQ0KAbkgf/6388dhde501IFoaf219jgVM0o3vFUSBh7bbZFuXUICoj9rXBinQpoZGGTZPwmkgbOjI59H7kjE/fCvLEZqalwdlLCE/+jCkTRmE+7a30c2CZKyWRCU5zqczs3wFvYyV3PeVz65cwu79MPiizHUt9XoabeNM/1UNCWvYGoC0ejDG636R2Ber2CCPjeerPXrvOrbSkuDInb1AaVw+ytBIZOa7pHvlFduuatiIoZTRdPoMcbG0aLEET9LJOufDgT/Ax42DGDxvjRetjchQSOvG1Yahp9RiZb4ZFRDHH2BrXmD9sibx/47Vmu/DlKbgSNzzWxMGefl/W2Qfx7h5bfDzE2wtq0DPRL2loP+PyPj0KQZYIURq0kyI9BSh47c8kncv/iEhT66+HHAXDPQJb9tl8Pgunro6TizPWL94k2dh9S0T3uKcMOz1ExjB9kChmC8O80UjvW7rrBx1FVeCUFRvGRoYehB6AV/MR2AZmP8HH4Weo35l0C3rAA4DGrxJE3c0aDbcwYYMeZpZohP+g1W/X+klcLfmihQdYUA=
