jobs:
  include:
    - stage: deploy-native-windows
      os: windows
      language: shell
      before_install:
        - echo ${TRAVIS_BUILD_DIR}
        - powershell -command 'Set-MpPreference -DisableRealtimeMonitoring $true'
        - powershell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'
        - choco install windows-sdk-10-version-1809-all
        - git clone https://github.com/portapps/portapps ${TRAVIS_BUILD_DIR}/../portapps
        - source ${TRAVIS_BUILD_DIR}/../portapps/.travis/prepare.sh
        - bash ${TRAVIS_BUILD_DIR}/../portapps/.travis/java.sh
      script:
        - "powerShell -Command '${TRAVIS_BUILD_DIR}/gradlew.bat native-cli:uploadDistro'"
      deploy:
        - provider: script
          skip_cleanup: true
          script: "./gradlew native-cli:uploadDistro"
          on:
            branch: master
    - stage: deploy-native-mac
      os: osx
      language: java
      osx_image: xcode11
      script:
      - travis_wait 40 ./gradlew native-cli:distro
      deploy:
      - provider: script
        skip_cleanup: true
        script: "./gradlew native-cli:uploadDistro"
        on:
          branch: master
    - stage: deploy-native-linux
      os: linux
      language: java
      jdk: openjdk8
      script:
      - travis_wait 40 ./gradlew native-cli:distro
      deploy:
      - provider: script
        skip_cleanup: true
        script: "./gradlew native-cli:uploadDistro"
        on:
          branch: master

#Token is encrypted
notifications:
  slack:
    rooms:
      secure: drSh4Et3zGIIi7S7x8bUl+r0CZzV/7mTW6qbnzFmDBq5Lii73C0W86HWS8LD9mdmX8hFl/n5ySMH6P1t+9dXzmSOBNg3gnVm4F4iLCMPMb5bzIjFA3S9PKVONCHNvYfINurFhT8drVsBYcrkTcg0+FkxzJcNsbUe5IGz+xtV5jI+XUN2xmVP5/Fphshv87c86btB7shbOUzAZBCZ+LWl9SGNCsXz3lqnOmLQEKBDRN/CxpDmEQ/q5KMbV0uoXBRF1+Ab/NxY1ZeUC8qugEUoxHr2KkrWYoDWhjEty2nP8kxKy9e7i6uVu1VLKhX4TaLy9J/eWD+Vr22ByFyfFVmANgg0/zUNP9uEiPUpoo3Xdvx2cgQESYbI9rZoWo2QDDEwSFoF3YNZ7nBIrMQLJlJ8aNF/dN2QZxyMbrXlVdPw95MxAhOTroYQbMSdTnctA7iCkJqPkF67ECF21hIJQ3/oTHjcH7QWUn2aTUo4Y7UQq9gvjabDzipMfUmGmAkai+WVoDBNWQMUeRzyYuKIB6ZVWM+Hi9hn+udj/Tl6+TJSADxk1HyFHKFdTOh9QWKEd2IHdgqlM+WMLy+SdjA28xro2h5Z2VWrUcDEm/pWEetooysBoXFrc2nm9/vG5QzDxCA8Fpd86QEbu8uMP9SquXW+snVyVjSfo/yltkkGqsIYDBI=
