# This is a basic workflow to help you get started with Actions

name: Build Native CLI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  OSX_LINUX:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
          java-version: 11

    # Runs a single command using the runners shell
    - name: Run native image
      run: ./gradlew build

    # Runs a set of commands using the runners shell
    - name: Create Native Image
      run: ./gradlew native-cli:nativeImage

  WINDOWS:
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
#      - name: install visualstudio2017
#        run: choco install visualstudio2017-workload-vctools
#      - name: version
#        run: dir "C:\Program Files (x86)\Microsoft Visual Studio"
#      - name: list it
#        run: dir "C:\Program Files (x86)\Microsoft Visual Studio\2017"
#      - name: list it1
#        run: dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
#      - name: list it2
#        run: dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC"
#      - name: list it3
#        run: dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary"
#      - name: testit
#        run: dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build"
#      #    - name: print page size
#      #      run: wmic pagefile list /format:list
#      #    - name: configure Pagefile
#      #      uses: al-cheb/configure-pagefile-action@v1.2

      - name: Build Native Image On Windows
        run: ./gradlew -d --stacktrace --scan native-cli:nativeImage
#        shell: cmd