name: Release DataWeave Native CLI
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  RELEASE_EXTENSION:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-2019]
        include:
          - os: windows-2019
            script_name: dw.exe
          - os: ubuntu-latest
            script_name: dw
          - os: macos-latest
            script_name: dw

    runs-on: ${{ matrix.os }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Runs a single command using the runners shell
      - name: Run native image
        run: ./gradlew build
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY}}

      # Runs a set of commands using the runners shell
      - name: Create Native Image
        run: ./gradlew native-cli:nativeImage

      - name: Artifact version
        id: artifact_version
        run: echo "::set-env name=NATIVE_VERSION::$(echo '${{github.ref}}' | sed -e 's,.*/v\(.*\),\1,')"

      # Upload the artifact file
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: native-cli/build/graal/${{ matrix.script_name }}
          asset_name: data-weave-${{env.NATIVE_VERSION}}-${{runner.os}}
          tag: ${{ github.ref }}
          overwrite: true

