# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
          java-version: 1.8

    - name: version
      run: dir "C:\Program Files (x86)\Microsoft Visual Studio"
    - name: list it
      run: dir "C:\Program Files (x86)\Microsoft Visual Studio\2019"
    - name: list it1
      run: dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"
    - name: list it2
      run: dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC"
    - name: list it3
      run: dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary"
    - name: testit
      run: dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build"
    - name: print page size
      run: wmic pagefile list /format:list
    - name: configure Pagefile
      uses: al-cheb/configure-pagefile-action@v1.2
    - name: Build Native Image On Windows
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
        gradlew build -x
        gradlew native-cli:nativeImage
      shell: cmd